// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/remind/remind.proto

package remind_service // import "rpc/remind/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RemindInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	RemindType           int32    `protobuf:"varint,2,opt,name=remind_type,json=remindType" json:"remind_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemindInfo) Reset()         { *m = RemindInfo{} }
func (m *RemindInfo) String() string { return proto.CompactTextString(m) }
func (*RemindInfo) ProtoMessage()    {}
func (*RemindInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_remind_8693d666db9379de, []int{0}
}
func (m *RemindInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemindInfo.Unmarshal(m, b)
}
func (m *RemindInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemindInfo.Marshal(b, m, deterministic)
}
func (dst *RemindInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemindInfo.Merge(dst, src)
}
func (m *RemindInfo) XXX_Size() int {
	return xxx_messageInfo_RemindInfo.Size(m)
}
func (m *RemindInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RemindInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RemindInfo proto.InternalMessageInfo

func (m *RemindInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RemindInfo) GetRemindType() int32 {
	if m != nil {
		return m.RemindType
	}
	return 0
}

type RemindRequest struct {
	RemindInfo           *RemindInfo `protobuf:"bytes,1,opt,name=remind_info,json=remindInfo" json:"remind_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RemindRequest) Reset()         { *m = RemindRequest{} }
func (m *RemindRequest) String() string { return proto.CompactTextString(m) }
func (*RemindRequest) ProtoMessage()    {}
func (*RemindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_remind_8693d666db9379de, []int{1}
}
func (m *RemindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemindRequest.Unmarshal(m, b)
}
func (m *RemindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemindRequest.Marshal(b, m, deterministic)
}
func (dst *RemindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemindRequest.Merge(dst, src)
}
func (m *RemindRequest) XXX_Size() int {
	return xxx_messageInfo_RemindRequest.Size(m)
}
func (m *RemindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemindRequest proto.InternalMessageInfo

func (m *RemindRequest) GetRemindInfo() *RemindInfo {
	if m != nil {
		return m.RemindInfo
	}
	return nil
}

type RemindBatchRequest struct {
	Uids                 []int64  `protobuf:"varint,1,rep,packed,name=uids" json:"uids,omitempty"`
	RemindType           int32    `protobuf:"varint,2,opt,name=remind_type,json=remindType" json:"remind_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemindBatchRequest) Reset()         { *m = RemindBatchRequest{} }
func (m *RemindBatchRequest) String() string { return proto.CompactTextString(m) }
func (*RemindBatchRequest) ProtoMessage()    {}
func (*RemindBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_remind_8693d666db9379de, []int{2}
}
func (m *RemindBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemindBatchRequest.Unmarshal(m, b)
}
func (m *RemindBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemindBatchRequest.Marshal(b, m, deterministic)
}
func (dst *RemindBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemindBatchRequest.Merge(dst, src)
}
func (m *RemindBatchRequest) XXX_Size() int {
	return xxx_messageInfo_RemindBatchRequest.Size(m)
}
func (m *RemindBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemindBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemindBatchRequest proto.InternalMessageInfo

func (m *RemindBatchRequest) GetUids() []int64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

func (m *RemindBatchRequest) GetRemindType() int32 {
	if m != nil {
		return m.RemindType
	}
	return 0
}

type CheckResponse struct {
	Unread               bool     `protobuf:"varint,1,opt,name=unread" json:"unread,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_remind_8693d666db9379de, []int{3}
}
func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (dst *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(dst, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetUnread() bool {
	if m != nil {
		return m.Unread
	}
	return false
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_remind_8693d666db9379de, []int{4}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RemindInfo)(nil), "remind.RemindInfo")
	proto.RegisterType((*RemindRequest)(nil), "remind.RemindRequest")
	proto.RegisterType((*RemindBatchRequest)(nil), "remind.RemindBatchRequest")
	proto.RegisterType((*CheckResponse)(nil), "remind.CheckResponse")
	proto.RegisterType((*EmptyResponse)(nil), "remind.EmptyResponse")
}

func init() { proto.RegisterFile("proto/remind/remind.proto", fileDescriptor_remind_8693d666db9379de) }

var fileDescriptor_remind_8693d666db9379de = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x8d, 0x06, 0x9d, 0x34, 0x2a, 0x03, 0x4a, 0x2c, 0xa2, 0x21, 0x17, 0x73, 0xaa, 0xd0,
	0x82, 0x28, 0x1e, 0xa4, 0x1f, 0x1e, 0x7a, 0x5d, 0xf5, 0xe2, 0x45, 0xda, 0xec, 0x94, 0x06, 0x6d,
	0xb2, 0x6e, 0x36, 0x85, 0xdc, 0xfc, 0xe9, 0xd2, 0xdd, 0x44, 0x0d, 0x28, 0xda, 0xd3, 0xbe, 0x99,
	0x9d, 0xf7, 0x66, 0xde, 0x30, 0x70, 0x2c, 0x64, 0xa6, 0xb2, 0x0b, 0x49, 0xcb, 0x24, 0xe5, 0xd5,
	0xd3, 0xd5, 0x39, 0x74, 0x4c, 0x14, 0xde, 0x02, 0x30, 0x8d, 0x26, 0xe9, 0x3c, 0xc3, 0x03, 0xb0,
	0x8b, 0x84, 0xfb, 0x56, 0x60, 0x45, 0x36, 0x5b, 0x43, 0x3c, 0x03, 0xd7, 0x54, 0x3e, 0xab, 0x52,
	0x90, 0xdf, 0x0a, 0xac, 0x68, 0x9b, 0x81, 0x49, 0x3d, 0x94, 0x82, 0xc2, 0x31, 0x78, 0x46, 0x80,
	0xd1, 0x5b, 0x41, 0xb9, 0xc2, 0xfe, 0x27, 0x23, 0x49, 0xe7, 0x99, 0xd6, 0x72, 0x7b, 0xd8, 0xad,
	0xba, 0x7f, 0x35, 0xab, 0x55, 0xd6, 0x38, 0x9c, 0x00, 0x9a, 0x9f, 0xe1, 0x54, 0xc5, 0x8b, 0x5a,
	0x0a, 0x61, 0xab, 0x48, 0x78, 0xee, 0x5b, 0x81, 0x1d, 0xd9, 0x4c, 0xe3, 0xbf, 0x07, 0x3a, 0x07,
	0x6f, 0xb4, 0xa0, 0xf8, 0x85, 0x51, 0x2e, 0xb2, 0x34, 0x27, 0x3c, 0x02, 0xa7, 0x48, 0x25, 0x4d,
	0x8d, 0xaf, 0x1d, 0x56, 0x45, 0xe1, 0x3e, 0x78, 0x77, 0x4b, 0xa1, 0xca, 0xba, 0xb0, 0xf7, 0xde,
	0x82, 0xb6, 0x99, 0xe2, 0x9e, 0xe4, 0x8a, 0x24, 0x5e, 0xc2, 0xee, 0x80, 0xf3, 0x47, 0x5d, 0x8e,
	0x3f, 0x58, 0xe8, 0x1c, 0xd6, 0xb9, 0x86, 0x10, 0x8e, 0x60, 0x6f, 0xc0, 0x8d, 0x95, 0x8a, 0xdc,
	0x69, 0x92, 0xbf, 0xbb, 0xfc, 0x4d, 0xe4, 0x1a, 0xda, 0x63, 0x7a, 0x25, 0x45, 0x9b, 0xf7, 0xbf,
	0x02, 0x57, 0xaf, 0xe0, 0x3f, 0xcc, 0xc6, 0xae, 0x86, 0xa7, 0x4f, 0x27, 0x52, 0xc4, 0xf5, 0xc5,
	0x88, 0xd9, 0x4d, 0xb5, 0xeb, 0x9c, 0xe4, 0x2a, 0x89, 0x69, 0xe6, 0xe8, 0xeb, 0xe9, 0x7f, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xf0, 0xc3, 0xdc, 0x3a, 0x5a, 0x02, 0x00, 0x00,
}
